### ISSUE TITLE
PDAL version 2.2

### ISSUE THREAD

**Issue by runette** [Simverge/pdal-unity#1]
Hi

I like what you have done. I want to use it - but in my project, I need it to work with GDAL 3.0.4 and it just does not work - it looks like the PDAL version 1.7 that you integrated to GDAL 203 (it looks like) will not work with GDAL 3.0.4 and the versions of the dlls that it needs  - I get "the specified procedure could not be found".

I want to update PDAL to 2.1.0. I can get the PDAL 2.1.0 dlls to run together with the GDAl 3.0.4 dlls - I can load pdalcpp.dll and pdal-util.dll and I can even get pdalc.dll loaded and  get it to report on the versions etc.

When I try to create a pipeline - it just crashes badly.  I am guessing because the API has changed.

Do you know what would be involved in completing the update. Where, for instance, does pdalc.dll come from ?

Thanks

Paul

**Comment by jimmysoda** [comment]
Hi @runette, please pardon the late reply.

The pdalc library is from [Simverge/pdal-c](https://github.com/Simverge/pdal-c), which is also forked at [PDAL/CAPI](https://github.com/PDAL/CAPI). It's a simple C interop wrapper for PDAL so the latter can be used in C#.

I haven't updated either pdal-c or pdal-unity in a long time. I pushed this repository to GitHub as a quick howto demonstration. The pdal-c library is also available in vcpkg but I think the CMake integration needs some work, e.g., its missing the config files for `find_package`.

I will not be able to update either pdal-c or pdal-unity anytime soon, nevertheless, you are free to fork and modify these projects as needed. I would be glad to review and accept any updates you wish to contribute as PRs. I recommend starting with stepping up pdal-c's [dependency Dockerfiles](https://github.com/Simverge/pdal-c/tree/master/tests/docker) to the PDAL version you wish to target and identify what breaks.

**Comment by runette** [comment]
Thanks. I guess I should have thought of looking in your other reps for
pdalc :)
