### ISSUE TITLE
Update Versions

### ISSUE THREAD

**Issue by runette** [Simverge/pdal-unity#2]
I worked all of the updated dependencies for my project - It just needed the PDAL/capi version of pdalc.dll to be compiled against the latest version of PDAL (2.1.0) and the dependent version of GDAL (3.0.4 - not quite the latest) and PROJ (6.1 for GDAL and 7.0 for GeoTIFF).

Since, although this project is only a demonstrator, it is the best place to find out how to integrate PDAL into Unity - I will pay back by sending a PR with the latest versions.

**Comment by jimmysoda** [comment]
Thanks @runette! I'll take a look at the PR (#3) in a few hours.
